import {
  EditDisplayFailureSchema,
  TaskDisplayFailureSchema,
  ExitPlanModeDisplayFailureSchema,
  PlainToolOutputSchema,
} from "./displayContracts";
import {
  AskUserQuestionDisplayInputSchema,
  AskUserQuestionDisplayResultSchema,
  BashDisplayFailureSchema,
  BashDisplayInputSchema,
  BashDisplayResultSchema,
  BashOutputDisplayInputSchema,
  BashOutputDisplayResultSchema,
  EditDisplayInputSchema,
  EditDisplayResultSchema,
  ExecDisplayInputSchema,
  ExecDisplayResultSchema,
  ExitPlanModeDisplayInputSchema,
  ExitPlanModeDisplayResultSchema,
  GlobDisplayInputSchema,
  GlobDisplayResultSchema,
  GoalDisplayInputSchema,
  GoalDisplayResultSchema,
  GrepDisplayInputSchema,
  GrepDisplayResultSchema,
  KillShellDisplayInputSchema,
  KillShellDisplayResultSchema,
  ReadDisplayInputSchema,
  ReadDisplayResultSchema,
  SpawnAgentDisplayInputSchema,
  SpawnAgentDisplayResultSchema,
  TaskDisplayInputSchema,
  TaskDisplayResultSchema,
  TaskListDisplayInputSchema,
  TaskListDisplayResultSchema,
  TaskOutputDisplayInputSchema,
  TaskOutputDisplayResultSchema,
  TodoWriteDisplayInputSchema,
  TodoWriteDisplayResultSchema,
  UpdatePlanDisplayInputSchema,
  UpdatePlanDisplayResultSchema,
  ViewImageDisplayInputSchema,
  ViewImageDisplayResultSchema,
  WebDisplayInputSchema,
  WebDisplayResultSchema,
  WebFetchDisplayInputSchema,
  WebFetchDisplayResultSchema,
  WebSearchDisplayInputSchema,
  WebSearchDisplayResultSchema,
  WriteDisplayInputSchema,
  WriteDisplayResultSchema,
  WriteStdinDisplayInputSchema,
  WriteStdinDisplayResultSchema,
} from "./displayContracts";

/** Authoritative data-only contracts. The mounted registry must cover every key. */
export const toolDisplayContracts = {
  TodoWrite: {
    partialResult: PlainToolOutputSchema,
    input: TodoWriteDisplayInputSchema,
    result: TodoWriteDisplayResultSchema,
    variants: ["standard", "plain-text"],
    standaloneResult: true,
  },
  TaskOutput: {
    partialResult: PlainToolOutputSchema,
    input: TaskOutputDisplayInputSchema,
    result: TaskOutputDisplayResultSchema,
    variants: ["standard", "plain-text"],
    standaloneResult: true,
  },
  AskUserQuestion: {
    partialResult: PlainToolOutputSchema,
    input: AskUserQuestionDisplayInputSchema,
    result: AskUserQuestionDisplayResultSchema,
    variants: ["standard", "plain-text"],
    standaloneResult: true,
  },
  Glob: {
    partialResult: PlainToolOutputSchema,
    input: GlobDisplayInputSchema,
    result: GlobDisplayResultSchema,
    variants: ["standard", "plain-text"],
    standaloneResult: true,
  },
  WebFetch: {
    partialResult: PlainToolOutputSchema,
    input: WebFetchDisplayInputSchema,
    result: WebFetchDisplayResultSchema,
    variants: ["standard", "plain-text"],
    standaloneResult: true,
  },
  ExitPlanMode: {
    partialResult: PlainToolOutputSchema,
    input: ExitPlanModeDisplayInputSchema,
    result: ExitPlanModeDisplayResultSchema,
    failure: ExitPlanModeDisplayFailureSchema,
    standaloneResultSchema: ExitPlanModeDisplayResultSchema.refine((value) =>
      Boolean(value.plan || value._renderedHtml || value.message),
    ),
    variants: ["standard", "plain-text"],
    standaloneResult: true,
  },
  Exec: {
    input: ExecDisplayInputSchema,
    result: ExecDisplayResultSchema,
    variants: ["standard"],
    standaloneResult: true,
  },
  Web: {
    input: WebDisplayInputSchema,
    result: WebDisplayResultSchema,
    variants: ["standard"],
    standaloneResult: true,
  },
  UpdatePlan: {
    input: UpdatePlanDisplayInputSchema,
    result: UpdatePlanDisplayResultSchema,
    failure: UpdatePlanDisplayResultSchema,
    standaloneResultSchema: UpdatePlanDisplayResultSchema.refine((value) =>
      typeof value === "string"
        ? value.trim().length > 0
        : Array.isArray(value)
          ? value.some((block) => block.text.trim().length > 0)
          : Boolean(value.message?.trim()),
    ),
    variants: ["standard"],
    standaloneResult: true,
  },
  Read: {
    partialResult: PlainToolOutputSchema,
    input: ReadDisplayInputSchema,
    result: ReadDisplayResultSchema,
    variants: ["text", "dedup", "image", "pdf", "plain-text"],
    standaloneResult: true,
  },
  ViewImage: {
    input: ViewImageDisplayInputSchema,
    result: ViewImageDisplayResultSchema,
    variants: ["standard"],
    standaloneResult: false,
  },
  Task: {
    partialResult: PlainToolOutputSchema,
    input: TaskDisplayInputSchema,
    result: TaskDisplayResultSchema,
    failure: TaskDisplayFailureSchema,
    variants: ["standard", "asynchronous", "plain-text"],
    standaloneResult: false,
  },
  Grep: {
    partialResult: PlainToolOutputSchema,
    input: GrepDisplayInputSchema,
    result: GrepDisplayResultSchema,
    variants: ["files", "content", "count", "plain-text"],
    standaloneResult: true,
  },
  Bash: {
    input: BashDisplayInputSchema,
    result: BashDisplayResultSchema,
    failure: BashDisplayFailureSchema,
    variants: ["standard"],
    standaloneResult: true,
  },
  WebSearch: {
    partialResult: PlainToolOutputSchema,
    input: WebSearchDisplayInputSchema,
    result: WebSearchDisplayResultSchema,
    variants: ["standard", "plain-text"],
    standaloneResult: true,
  },
  spawn_agent: {
    input: SpawnAgentDisplayInputSchema,
    result: SpawnAgentDisplayResultSchema,
    failure: SpawnAgentDisplayResultSchema,
    variants: ["standard"],
    standaloneResult: false,
  },
  Write: {
    input: WriteDisplayInputSchema,
    result: WriteDisplayResultSchema,
    variants: ["file", "acknowledgement"],
    standaloneResult: true,
  },
  TaskCreate: {
    input: TaskListDisplayInputSchema,
    result: TaskListDisplayResultSchema,
    variants: ["event", "snapshot"],
    standaloneResult: true,
  },
  TaskUpdate: {
    input: TaskListDisplayInputSchema,
    result: TaskListDisplayResultSchema,
    variants: ["event", "snapshot"],
    standaloneResult: true,
  },
  WriteStdin: {
    input: WriteStdinDisplayInputSchema,
    result: WriteStdinDisplayResultSchema,
    // Failed command polls carry the same output/exit metadata as successes.
    // The Shell renderer already preserves their error styling and status.
    failure: WriteStdinDisplayResultSchema,
    variants: ["standard"],
    standaloneResult: true,
  },
  BashOutput: {
    partialResult: PlainToolOutputSchema,
    input: BashOutputDisplayInputSchema,
    result: BashOutputDisplayResultSchema,
    variants: ["standard", "plain-text"],
    standaloneResult: true,
  },
  KillShell: {
    partialResult: PlainToolOutputSchema,
    input: KillShellDisplayInputSchema,
    result: KillShellDisplayResultSchema,
    variants: ["standard", "plain-text"],
    standaloneResult: true,
  },
  Edit: {
    partialResult: PlainToolOutputSchema,
    input: EditDisplayInputSchema,
    result: EditDisplayResultSchema,
    failure: EditDisplayFailureSchema,
    standaloneResultSchema: EditDisplayResultSchema.refine(
      (value) =>
        value.filePath !== undefined ||
        value.structuredPatch !== undefined ||
        value.content !== undefined,
    ),
    variants: [
      "replacement",
      "patch",
      "augmented",
      "changes",
      "target",
      "plain-text",
    ],
    standaloneResult: true,
  },
  create_goal: {
    input: GoalDisplayInputSchema,
    result: GoalDisplayResultSchema,
    failure: GoalDisplayResultSchema,
    variants: ["standard"],
    standaloneResult: true,
  },
  get_goal: {
    input: GoalDisplayInputSchema,
    result: GoalDisplayResultSchema,
    failure: GoalDisplayResultSchema,
    variants: ["standard"],
    standaloneResult: true,
  },
  update_goal: {
    input: GoalDisplayInputSchema,
    result: GoalDisplayResultSchema,
    failure: GoalDisplayResultSchema,
    variants: ["standard"],
    standaloneResult: true,
  },
} as const;
export type ToolDisplayName = keyof typeof toolDisplayContracts;
